import { Hono } from 'hono';
import { corsMiddleware } from './middleware/cors.js';
import { rateLimitMiddleware } from './middleware/rateLimit.js';
import { authMiddleware } from './middleware/auth.js';
import { authRoutes } from './routes/auth.js';
import { userRoutes } from './routes/users.js';
import { chatRoutes } from './routes/chats.js';
import { messageRoutes } from './routes/messages.js';
import { mediaRoutes } from './routes/media.js';
import { aiRoutes } from './routes/ai.js';
import { serveFrontend } from './routes/frontend.js';
import { ChatRoom } from './do/chat-room.js';
import { serviceWorker, icon192, icon512 } from './static/pwa-assets.js';
import css from './static/css/style.js';
import js from './static/app-bundle.js';

const app = new Hono();
app.use('*', corsMiddleware);
app.use('*', rateLimitMiddleware);
app.get('/api/health', c => c.json({ status: 'ok', app: 'ChatLK', timestamp: Date.now() }));
app.route('/api/auth', authRoutes);
app.get('/ws', async c => {
  const userId = c.req.query('userId');
  const chatId = c.req.query('chatId');
  const token = c.req.query('token');
  if (!userId || !chatId || !token) return c.json({ error: 'Missing credentials' }, 400);
  const id = c.env.CHAT_ROOM.idFromName(chatId);
  return c.env.CHAT_ROOM.get(id).fetch(c.req.raw);
});
app.use('/api/*', authMiddleware);
app.route('/api/users', userRoutes);
app.route('/api/chats', chatRoutes);
app.route('/api/messages', messageRoutes);
app.route('/api/media', mediaRoutes);
app.route('/api/ai', aiRoutes);
app.get('/manifest.json', c => c.json({ name: 'ChatLK', short_name: 'ChatLK', start_url: '/', display: 'standalone', background_color: '#0b141a', theme_color: '#25d366', icons: [{ src: '/icon-192.svg', sizes: '192x192', type: 'image/svg+xml' }, { src: '/icon-512.svg', sizes: '512x512', type: 'image/svg+xml' }] }));
app.get('/style.css', c => c.body(css, { headers: { 'content-type': 'text/css' } }));
app.get('/app.js', c => c.body(js, { headers: { 'content-type': 'application/javascript' } }));
app.get('/sw.js', c => c.body(serviceWorker, { headers: { 'content-type': 'application/javascript' } }));
app.get('/icon-192.svg', c => c.body(icon192, { headers: { 'content-type': 'image/svg+xml' } }));
app.get('/icon-512.svg', c => c.body(icon512, { headers: { 'content-type': 'image/svg+xml' } }));
app.get('/', serveFrontend);
app.get('*', serveFrontend);

export { ChatRoom };
export default app;
