/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R1xbetRouteImport } from './routes/1xbet'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CasinoRouteImport } from './routes/casino'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as LiveBetRouteImport } from './routes/live-bet'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as WithdrawRouteImport } from './routes/withdraw'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R1xbetRoute = R1xbetRouteImport.update({
  id: '/1xbet',
  path: '/1xbet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoRoute = CasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveBetRoute = LiveBetRouteImport.update({
  id: '/live-bet',
  path: '/live-bet',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/1xbet': typeof R1xbetRoute
  '/admin': typeof AdminRoute
  '/casino': typeof CasinoRoute
  '/deposit': typeof DepositRoute
  '/live-bet': typeof LiveBetRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/promotions': typeof PromotionsRoute
  '/register': typeof RegisterRoute
  '/sports': typeof SportsRoute
  '/support': typeof SupportRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/1xbet': typeof R1xbetRoute
  '/admin': typeof AdminRoute
  '/casino': typeof CasinoRoute
  '/deposit': typeof DepositRoute
  '/live-bet': typeof LiveBetRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/promotions': typeof PromotionsRoute
  '/register': typeof RegisterRoute
  '/sports': typeof SportsRoute
  '/support': typeof SupportRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/1xbet': typeof R1xbetRoute
  '/admin': typeof AdminRoute
  '/casino': typeof CasinoRoute
  '/deposit': typeof DepositRoute
  '/live-bet': typeof LiveBetRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/promotions': typeof PromotionsRoute
  '/register': typeof RegisterRoute
  '/sports': typeof SportsRoute
  '/support': typeof SupportRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/1xbet'
    | '/admin'
    | '/casino'
    | '/deposit'
    | '/live-bet'
    | '/login'
    | '/privacy-policy'
    | '/promotions'
    | '/register'
    | '/sports'
    | '/support'
    | '/transactions'
    | '/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/1xbet'
    | '/admin'
    | '/casino'
    | '/deposit'
    | '/live-bet'
    | '/login'
    | '/privacy-policy'
    | '/promotions'
    | '/register'
    | '/sports'
    | '/support'
    | '/transactions'
    | '/withdraw'
  id:
    | '__root__'
    | '/'
    | '/1xbet'
    | '/admin'
    | '/casino'
    | '/deposit'
    | '/live-bet'
    | '/login'
    | '/privacy-policy'
    | '/promotions'
    | '/register'
    | '/sports'
    | '/support'
    | '/transactions'
    | '/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R1xbetRoute: typeof R1xbetRoute
  AdminRoute: typeof AdminRoute
  CasinoRoute: typeof CasinoRoute
  DepositRoute: typeof DepositRoute
  LiveBetRoute: typeof LiveBetRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PromotionsRoute: typeof PromotionsRoute
  RegisterRoute: typeof RegisterRoute
  SportsRoute: typeof SportsRoute
  SupportRoute: typeof SupportRoute
  TransactionsRoute: typeof TransactionsRoute
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/1xbet': {
      id: '/1xbet'
      path: '/1xbet'
      fullPath: '/1xbet'
      preLoaderRoute: typeof R1xbetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino': {
      id: '/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof CasinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-bet': {
      id: '/live-bet'
      path: '/live-bet'
      fullPath: '/live-bet'
      preLoaderRoute: typeof LiveBetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R1xbetRoute: R1xbetRoute,
  AdminRoute: AdminRoute,
  CasinoRoute: CasinoRoute,
  DepositRoute: DepositRoute,
  LiveBetRoute: LiveBetRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PromotionsRoute: PromotionsRoute,
  RegisterRoute: RegisterRoute,
  SportsRoute: SportsRoute,
  SupportRoute: SupportRoute,
  TransactionsRoute: TransactionsRoute,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
